/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.ActivityMailUserLinkDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_activity_mail_user_link</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_activity_mail_user_link.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface ActivityMailUserLinkMapper  extends BaseMapper<ActivityMailUserLinkDO>{
	/**
	 *  Query DB table <tt>gtc_activity_mail_user_link</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, activity_id, mail_user_id, gmt_create, gmt_modified, enabled from gtc_activity_mail_user_link where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return ActivityMailUserLinkDO
	 *	@throws DataAccessException
	 */	 

		public ActivityMailUserLinkDO getById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_activity_mail_user_link</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_activity_mail_user_link set enabled=?, gmt_modified=now() where (id = ?)</tt>
	 *
	 *	@param enabled 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int modifyEnabled(@Param("enabled")boolean enabled , @Param("id")long id) throws DataAccessException;

}