/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.AppConfigDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>gtc_app_config</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_app_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface AppConfigMapper  extends BaseMapper<AppConfigDO>{
	/**
	 *  Query DB table <tt>gtc_app_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_code, app_name, notify_url, memo, status, properties, gmt_create, gmt_modified from gtc_app_config where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return AppConfigDO
	 *	@throws DataAccessException
	 */	 

		public AppConfigDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_app_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_code, app_name, notify_url, memo, status, properties, gmt_create, gmt_modified from gtc_app_config</tt>
	 *
	 *	@return List<AppConfigDO>
	 *	@throws DataAccessException
	 */	 

		public List<AppConfigDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_app_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_code, app_name, notify_url, memo, status, properties, gmt_create, gmt_modified from gtc_app_config where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<AppConfigDO>
	 *	@throws DataAccessException
	 */	 

		public List<AppConfigDO> selectByMaxGmtModifed(@Param("gmtModified")Date gmtModified) throws DataAccessException;

}