/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.AppSignKeyDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>gtc_app_sign_key</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_app_sign_key.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface AppSignKeyMapper  extends BaseMapper<AppSignKeyDO>{
	/**
	 *  Query DB table <tt>gtc_app_sign_key</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_id, key_type, key_value, gmt_create, gmt_modified, enabled from gtc_app_sign_key where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return AppSignKeyDO
	 *	@throws DataAccessException
	 */	 

		public AppSignKeyDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_app_sign_key</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_id, key_type, key_value, gmt_create, gmt_modified, enabled from gtc_app_sign_key</tt>
	 *
	 *	@return List<AppSignKeyDO>
	 *	@throws DataAccessException
	 */	 

		public List<AppSignKeyDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_app_sign_key</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_id, key_type, key_value, gmt_create, gmt_modified, enabled from gtc_app_sign_key where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<AppSignKeyDO>
	 *	@throws DataAccessException
	 */	 

		public List<AppSignKeyDO> selectByMaxGmtModifed(@Param("gmtModified")Date gmtModified) throws DataAccessException;

}