/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.BlackListDO;
import org.springframework.dao.DataAccessException;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_black_list</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_black_list.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface BlackListMapper  extends BaseMapper<BlackListDO>{
	/**
	 *  Query DB table <tt>gtc_black_list</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message_type, receiver, business_type, remark, gmt_create, gmt_modified from gtc_black_list where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return BlackListDO
	 *	@throws DataAccessException
	 */	 

		public BlackListDO getById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_black_list</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message_type, receiver, business_type, remark, gmt_create, gmt_modified from gtc_black_list</tt>
	 *
	 *	@return List<BlackListDO>
	 *	@throws DataAccessException
	 */	 

		public List<BlackListDO> findAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_black_list</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message_type, receiver, business_type, remark, gmt_create, gmt_modified from gtc_black_list where ((receiver = ?) AND (message_type = ?) AND (business_type = ?))</tt>
	 *
	 *	@param receiver 
	 *	@param messageType 
	 *	@param businessType 
	 *	@return BlackListDO
	 *	@throws DataAccessException
	 */	 

		public BlackListDO getByReceiverAndMsgType(@Param("receiver")String receiver , @Param("messageType")String messageType , @Param("businessType")String businessType) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>gtc_black_list</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from gtc_black_list where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int deleteById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_black_list</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message_type, receiver, business_type, remark, gmt_create, gmt_modified from gtc_black_list where ((message_type = ?) AND (receiver LIKE ?) AND (business_type LIKE ?)) order by receiver ASC</tt>
	 *
	 *	@param messageType 
	 *	@param receiver 
	 *	@param businessType 
	 *	@param page 
	 *	@return List<BlackListDO>
	 *	@throws DataAccessException
	 */	 

		public List<BlackListDO> findBlackListForPage(@Param("messageType")String messageType , @Param("receiver")String receiver , @Param("businessType")String businessType , @Param("page")Page<BlackListDO> page) throws DataAccessException;

}