/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.ChannelValidateCodeDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_channel_validate_code</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_channel_validate_code.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface ChannelValidateCodeMapper  extends BaseMapper<ChannelValidateCodeDO>{
	/**
	 *  Query DB table <tt>gtc_channel_validate_code</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, channel, channel_user_id, channel_user_name, validate_code, gmt_create, gmt_modified, validate_count, gmt_current_validate, gmt_last_validate, success_validated, gmt_validate_create, gmt_validate_success from gtc_channel_validate_code where ((channel = ?) AND (channel_user_id = ?))</tt>
	 *
	 *	@param channel 
	 *	@param channelUserId 
	 *	@return ChannelValidateCodeDO
	 *	@throws DataAccessException
	 */	 

		public ChannelValidateCodeDO selectByChannelAndChannelUserId(@Param("channel")String channel , @Param("channelUserId")String channelUserId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_channel_validate_code</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, channel, channel_user_id, channel_user_name, validate_code, gmt_create, gmt_modified, validate_count, gmt_current_validate, gmt_last_validate, success_validated, gmt_validate_create, gmt_validate_success from gtc_channel_validate_code where ((channel = ?) AND (channel_user_name = ?))</tt>
	 *
	 *	@param channel 
	 *	@param channelUserName 
	 *	@return ChannelValidateCodeDO
	 *	@throws DataAccessException
	 */	 

		public ChannelValidateCodeDO selectByChannelAndChannelUserName(@Param("channel")String channel , @Param("channelUserName")String channelUserName) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_channel_validate_code</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_channel_validate_code set validate_count=(validate_count + 1), success_validated=(success_validated + 1), gmt_last_validate=gmt_current_validate, gmt_current_validate=now(), gmt_modified=now(), gmt_validate_success=now() where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateValidateSuccess(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_channel_validate_code</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_channel_validate_code set validate_count=0, success_validated=0, gmt_current_validate=NULL, gmt_modified=now(), gmt_validate_create=now(), gmt_validate_success=NULL, validate_code=? where (id = ?)</tt>
	 *
	 *	@param validateCode 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateReadyToValidate(@Param("validateCode")String validateCode , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_channel_validate_code</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_channel_validate_code set validate_count=(validate_count + 1), gmt_current_validate=NULL, gmt_modified=now() where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateValidateFailed(@Param("id")long id) throws DataAccessException;

}