/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.MailSendClientDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_mail_send_client</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_send_client.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface MailSendClientMapper  extends BaseMapper<MailSendClientDO>{
	/**
	 *  Query DB table <tt>gtc_mail_send_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_id, gmt_create, gmt_modified, client_ip, gmt_live, current_amount, status, client_host from gtc_mail_send_client where (client_id = ?)</tt>
	 *
	 *	@param clientId 
	 *	@return MailSendClientDO
	 *	@throws DataAccessException
	 */	 

		public MailSendClientDO selectByClientId(@Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), status=?, gmt_live=now() where (client_id = ?)</tt>
	 *
	 *	@param status 
	 *	@param clientId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateStatusGmtLiveByClientId(@Param("status")String status , @Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), current_amount='addCurrentAmount' where (id = 'id')</tt>
	 *
	 *	@param addCurrentAmount 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int addCurrentAmountById(@Param("addCurrentAmount")long addCurrentAmount , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), current_amount='subtractCurrentAmount' where (id = 'id')</tt>
	 *
	 *	@param subtractCurrentAmount 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int subtractCurrentAmountById(@Param("subtractCurrentAmount")long subtractCurrentAmount , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set current_amount=1</tt>
	 *
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateCurrentAmountByMailTimeout() throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), status=? where (client_id = ?)</tt>
	 *
	 *	@param status 
	 *	@param clientId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateStatusByClientId(@Param("status")String status , @Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mail_send_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select status from gtc_mail_send_client where (client_id = ?)</tt>
	 *
	 *	@param clientId 
	 *	@return String
	 *	@throws DataAccessException
	 */	 

		public String selectStatusByClientId(@Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mail_send_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from gtc_mail_send_client where (client_id = ?)</tt>
	 *
	 *	@param clientId 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectIdByClientId(@Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now()</tt>
	 *
	 *	@param status 
	 *	@param seconds 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateStatusByGmtLive(@Param("status")String status , @Param("seconds")Integer seconds) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), status='DEAD'</tt>
	 *
	 *	@param timeoutSeconds 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateToDeadByTimeout(@Param("timeoutSeconds")int timeoutSeconds) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mail_send_client</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mail_send_client set gmt_modified=now(), gmt_live=sydate, status='LIVE' where (client_id = ?)</tt>
	 *
	 *	@param clientId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateGmtLiveByClientId(@Param("clientId")String clientId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mail_send_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_id, gmt_create, gmt_modified, client_ip, client_host, gmt_live, current_amount, status from gtc_mail_send_client where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return MailSendClientDO
	 *	@throws DataAccessException
	 */	 

		public MailSendClientDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mail_send_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, current_amount from gtc_mail_send_client where (status = ?)</tt>
	 *
	 *	@param status 
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 

		public List<Map<String,Object>> selectIdCurrentAmountByStatus(@Param("status")String status) throws DataAccessException;

}