/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.MobileClientPushMsgDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>gtc_mobile_client_push_msg</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mobile_client_push_msg.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface MobileClientPushMsgMapper  extends BaseMapper<MobileClientPushMsgDO>{
	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, content, gmt_create, gmt_modified, gmt_next_push, try_count, push_result, status, source_message_id, source_app_name, properties from gtc_mobile_client_push_msg where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return MobileClientPushMsgDO
	 *	@throws DataAccessException
	 */	 

		public MobileClientPushMsgDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from gtc_mobile_client_push_msg where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectCountById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, content, gmt_create, gmt_modified, gmt_next_push, try_count, push_result, status, source_message_id, source_app_name, properties from gtc_mobile_client_push_msg where (source_message_id = ?)</tt>
	 *
	 *	@param sourceMessageId 
	 *	@return MobileClientPushMsgDO
	 *	@throws DataAccessException
	 */	 

		public MobileClientPushMsgDO selectBySourceMessageId(@Param("sourceMessageId")String sourceMessageId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from gtc_mobile_client_push_msg where (1 = 0)</tt>
	 *
	 *	@param recordCount 
	 *	@return List<Long>
	 *	@throws DataAccessException
	 */	 

		public List<Long> selectReadyToSendIds(@Param("recordCount")int recordCount) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_mobile_client_push_msg</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_mobile_client_push_msg set gmt_next_push=?, try_count=(try_count + 1), push_result=?, status=? where (id = ?)</tt>
	 *
	 *	@param gmtNextPush 
	 *	@param pushResult 
	 *	@param status 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateSendRetryById(@Param("gmtNextPush")Date gmtNextPush , @Param("pushResult")String pushResult , @Param("status")String status , @Param("id")long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>gtc_mobile_client_push_msg</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from gtc_mobile_client_push_msg where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int deleteById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, content, gmt_create, gmt_modified, gmt_next_push, try_count, push_result, status, source_message_id, source_app_name, properties from gtc_mobile_client_push_msg where (1 = 0)</tt>
	 *
	 *	@param userId 
	 *	@param content 
	 *	@param pushResult 
	 *	@param status 
	 *	@param sourceMessageId 
	 *	@param properties 
	 *	@param gmtMinCreate 
	 *	@param gmtMaxCreate 
	 *	@param gmtMinModified 
	 *	@param gmtMaxModified 
	 *	@param gmtMinNextPush 
	 *	@param gmtMaxNextPush 
	 *	@param tryMinCount 
	 *	@param tryMaxCount 
	 *	@param page 
	 *	@return List<MobileClientPushMsgDO>
	 *	@throws DataAccessException
	 */	 

		public List<MobileClientPushMsgDO> select(@Param("userId")String userId , @Param("content")String content , @Param("pushResult")String pushResult , @Param("status")String status , @Param("sourceMessageId")String sourceMessageId , @Param("properties")String properties , @Param("gmtMinCreate")Date gmtMinCreate , @Param("gmtMaxCreate")Date gmtMaxCreate , @Param("gmtMinModified")Date gmtMinModified , @Param("gmtMaxModified")Date gmtMaxModified , @Param("gmtMinNextPush")Date gmtMinNextPush , @Param("gmtMaxNextPush")Date gmtMaxNextPush , @Param("tryMinCount")long tryMinCount , @Param("tryMaxCount")long tryMaxCount , @Param("page")Page<MobileClientPushMsgDO> page) throws DataAccessException;

}