/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.MobileClientPushMsgHisDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>gtc_mobile_client_push_msg_his</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mobile_client_push_msg_his.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface MobileClientPushMsgHisMapper  extends BaseMapper<MobileClientPushMsgHisDO>{
	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, content, gmt_create, gmt_modified, gmt_next_push, try_count, push_result, status, source_message_id, source_app_name, gmt_his_create, properties from gtc_mobile_client_push_msg_his where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return MobileClientPushMsgHisDO
	 *	@throws DataAccessException
	 */	 

		public MobileClientPushMsgHisDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_mobile_client_push_msg_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, content, gmt_create, gmt_modified, gmt_next_push, try_count, push_result, status, source_message_id, source_app_name, properties, gmt_his_create from gtc_mobile_client_push_msg_his where (1 = 0)</tt>
	 *
	 *	@param userId 
	 *	@param content 
	 *	@param pushResult 
	 *	@param status 
	 *	@param sourceMessageId 
	 *	@param properties 
	 *	@param gmtMinCreate 
	 *	@param gmtMaxCreate 
	 *	@param gmtMinModified 
	 *	@param gmtMaxModified 
	 *	@param gmtMinNextPush 
	 *	@param gmtMaxNextPush 
	 *	@param gmtMinHisCreate 
	 *	@param gmtMaxHisCreate 
	 *	@param tryMinCount 
	 *	@param tryMaxCount 
	 *	@param page 
	 *	@return List<MobileClientPushMsgHisDO>
	 *	@throws DataAccessException
	 */	 

		public List<MobileClientPushMsgHisDO> select(@Param("userId")String userId , @Param("content")String content , @Param("pushResult")String pushResult , @Param("status")String status , @Param("sourceMessageId")String sourceMessageId , @Param("properties")String properties , @Param("gmtMinCreate")Date gmtMinCreate , @Param("gmtMaxCreate")Date gmtMaxCreate , @Param("gmtMinModified")Date gmtMinModified , @Param("gmtMaxModified")Date gmtMaxModified , @Param("gmtMinNextPush")Date gmtMinNextPush , @Param("gmtMaxNextPush")Date gmtMaxNextPush , @Param("gmtMinHisCreate")Date gmtMinHisCreate , @Param("gmtMaxHisCreate")Date gmtMaxHisCreate , @Param("tryMinCount")long tryMinCount , @Param("tryMaxCount")long tryMaxCount , @Param("page")Page<MobileClientPushMsgHisDO> page) throws DataAccessException;

}