/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.SmsClientLogDO;
import org.springframework.dao.DataAccessException;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_sms_client_log</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_client_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface SmsClientLogMapper  extends BaseMapper<SmsClientLogDO>{
	/**
	 *  Query DB table <tt>gtc_sms_client_log</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_id, content, action, gmt_create, gmt_modified from gtc_sms_client_log where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return SmsClientLogDO
	 *	@throws DataAccessException
	 */	 

		public SmsClientLogDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_log</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_id, content, action, gmt_create, gmt_modified from gtc_sms_client_log where (1 = 0)</tt>
	 *
	 *	@param id 
	 *	@param smsClientSendId 
	 *	@param action 
	 *	@param page 
	 *	@return List<SmsClientLogDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientLogDO> search(@Param("id")long id , @Param("smsClientSendId")long smsClientSendId , @Param("action")String action , @Param("page")Page<SmsClientLogDO> page) throws DataAccessException;

}