/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.SmsClientSendDO;
import org.springframework.dao.DataAccessException;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_sms_client_send</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_client_send.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface SmsClientSendMapper  extends BaseMapper<SmsClientSendDO>{
	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return SmsClientSendDO
	 *	@throws DataAccessException
	 */	 

		public SmsClientSendDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (client_apply_batch_id = ?)</tt>
	 *
	 *	@param clientApplyBatchId 
	 *	@return List<SmsClientSendDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientSendDO> selectByClientApplyBatchId(@Param("clientApplyBatchId")long clientApplyBatchId) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (id = ?) for update</tt>
	 *
	 *	@param id 
	 *	@return SmsClientSendDO
	 *	@throws DataAccessException
	 */	 

		public SmsClientSendDO selectByIdForUpdate(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (1 = 0)</tt>
	 *
	 *	@param ids 
	 *	@return List<SmsClientSendDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientSendDO> selectByIdsForUpdate(@Param("ids")List<?> ids) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (1 = 0)</tt>
	 *
	 *	@param recordCount 
	 *	@return List<SmsClientSendDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientSendDO> selectReadyToSendForUpdate(@Param("recordCount")int recordCount) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client_send</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sms_id, status, gmt_create, gmt_modified, gmt_client_apply, client_no, client_apply_count, gmt_client_send_finish, gmt_client_resend, client_apply_batch_id from gtc_sms_client_send where (1 = 0)</tt>
	 *
	 *	@param id 
	 *	@param smsId 
	 *	@param status 
	 *	@param clientNo 
	 *	@param page 
	 *	@return List<SmsClientSendDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientSendDO> search(@Param("id")long id , @Param("smsId")long smsId , @Param("status")String status , @Param("clientNo")String clientNo , @Param("page")Page<SmsClientSendDO> page) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_sms_client_send</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_sms_client_send set gmt_modified=now(), status='RETRY', gmt_client_resend=now() where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateSendRetry(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_sms_client_send</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_sms_client_send set gmt_modified=now(), status='READY', gmt_client_resend=now(), client_apply_batch_id=0 where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateGiveupById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>gtc_sms_client_send</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from gtc_sms_client_send where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int deleteById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>gtc_sms_client_send</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update gtc_sms_client_send set gmt_modified=now() where (1 = 0)</tt>
	 *
	 *	@param clientNo 
	 *	@param clientApplyBatchId 
	 *	@param ids 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateSendingByIds(@Param("clientNo")String clientNo , @Param("clientApplyBatchId")long clientApplyBatchId , @Param("ids")List<?> ids) throws DataAccessException;

}