/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.SmsClientDO;
import org.springframework.dao.DataAccessException;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>gtc_sms_client</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_client.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface SmsClientMapper  extends BaseMapper<SmsClientDO>{
	/**
	 *  Query DB table <tt>gtc_sms_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_no, login_password, gmt_create, gmt_modified, enabled, sign_key, apply_each_count, apply_max_pool_size, sign_type from gtc_sms_client where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return SmsClientDO
	 *	@throws DataAccessException
	 */	 

		public SmsClientDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_no, login_password, gmt_create, gmt_modified, enabled, sign_key, apply_each_count, apply_max_pool_size, sign_type from gtc_sms_client where (client_no = ?)</tt>
	 *
	 *	@param clientNo 
	 *	@return SmsClientDO
	 *	@throws DataAccessException
	 */	 

		public SmsClientDO selectByClientNo(@Param("clientNo")String clientNo) throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_sms_client</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, client_no, login_password, gmt_create, gmt_modified, enabled, sign_key, apply_each_count, apply_max_pool_size, sign_type from gtc_sms_client where (1 = 0)</tt>
	 *
	 *	@param id 
	 *	@param clientNo 
	 *	@param enabled 
	 *	@param page 
	 *	@return List<SmsClientDO>
	 *	@throws DataAccessException
	 */	 

		public List<SmsClientDO> search(@Param("id")long id , @Param("clientNo")String clientNo , @Param("enabled")Boolean enabled , @Param("page")Page<SmsClientDO> page) throws DataAccessException;

}