/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.gotonecore.repository.entity.WxGenReplyMsgScriptDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>gtc_wx_gen_reply_msg_script</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_wx_gen_reply_msg_script.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
public interface WxGenReplyMsgScriptMapper  extends BaseMapper<WxGenReplyMsgScriptDO>{
	/**
	 *  Query DB table <tt>gtc_wx_gen_reply_msg_script</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select code, name, support_check_script, gen_reply_msg_script, enabled, gmt_modified, gmt_create, support_msg_type from gtc_wx_gen_reply_msg_script</tt>
	 *
	 *	@return List<WxGenReplyMsgScriptDO>
	 *	@throws DataAccessException
	 */	 

		public List<WxGenReplyMsgScriptDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>gtc_wx_gen_reply_msg_script</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select code, name, support_check_script, gen_reply_msg_script, enabled, gmt_modified, gmt_create, support_msg_type from gtc_wx_gen_reply_msg_script where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<WxGenReplyMsgScriptDO>
	 *	@throws DataAccessException
	 */	 

		public List<WxGenReplyMsgScriptDO> selectByMaxGmtModified(@Param("gmtModified")Date gmtModified) throws DataAccessException;

}