/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_channel_validate_code</tt>.<br>
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_channel_validate_code.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="ChannelValidateCodeDO对象", description="")
@TableName("gtc_channel_validate_code")
public class ChannelValidateCodeDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_CHANNEL_VALIDATE_CODE";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>channel</tt>.<br>
     */
	 public static final String COLUMN_CHANNEL = "channel";
	/**
	 * This constant corresponds to db column <tt>channel_user_id</tt>.<br>
     */
	 public static final String COLUMN_CHANNEL_USER_ID = "channel_user_id";
	/**
	 * This constant corresponds to db column <tt>channel_user_name</tt>.<br>
     */
	 public static final String COLUMN_CHANNEL_USER_NAME = "channel_user_name";
	/**
	 * This constant corresponds to db column <tt>validate_code</tt>.<br>
     */
	 public static final String COLUMN_VALIDATE_CODE = "validate_code";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>validate_count</tt>.<br>
     */
	 public static final String COLUMN_VALIDATE_COUNT = "validate_count";
	/**
	 * This constant corresponds to db column <tt>gmt_current_validate</tt>.<br>
     */
	 public static final String COLUMN_GMT_CURRENT_VALIDATE = "gmt_current_validate";
	/**
	 * This constant corresponds to db column <tt>gmt_last_validate</tt>.<br>
     */
	 public static final String COLUMN_GMT_LAST_VALIDATE = "gmt_last_validate";
	/**
	 * This constant corresponds to db column <tt>success_validated</tt>.<br>
     */
	 public static final String COLUMN_SUCCESS_VALIDATED = "success_validated";
	/**
	 * This constant corresponds to db column <tt>gmt_validate_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_VALIDATE_CREATE = "gmt_validate_create";
	/**
	 * This constant corresponds to db column <tt>gmt_validate_success</tt>.<br>
     */
	 public static final String COLUMN_GMT_VALIDATE_SUCCESS = "gmt_validate_success";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>channel</tt>.<br>
     * 
     */
	private String channel;
	
	/**
	 * This property corresponds to db column <tt>channel_user_id</tt>.<br>
     * 
     */
	private String channelUserId;
	
	/**
	 * This property corresponds to db column <tt>channel_user_name</tt>.<br>
     * 
     */
	private String channelUserName;
	
	/**
	 * This property corresponds to db column <tt>validate_code</tt>.<br>
     * 
     */
	private String validateCode;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>validate_count</tt>.<br>
     * 
     */
	private int validateCount;
	
	/**
	 * This property corresponds to db column <tt>gmt_current_validate</tt>.<br>
     * 
     */
	private Date gmtCurrentValidate;
	
	/**
	 * This property corresponds to db column <tt>gmt_last_validate</tt>.<br>
     * 
     */
	private Date gmtLastValidate;
	
	/**
	 * This property corresponds to db column <tt>success_validated</tt>.<br>
     * 
     */
	private boolean successValidated;
	
	/**
	 * This property corresponds to db column <tt>gmt_validate_create</tt>.<br>
     * 
     */
	private Date gmtValidateCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_validate_success</tt>.<br>
     * 
     */
	private Date gmtValidateSuccess;
	

    //========== getters and setters ==========

}
