/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_mail_send_client</tt>.<br>
 * 邮件发送客户端
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_send_client.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="MailSendClientDO对象", description="邮件发送客户端")
@TableName("gtc_mail_send_client")
public class MailSendClientDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_MAIL_SEND_CLIENT";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>client_id</tt>.<br>
     */
	 public static final String COLUMN_CLIENT_ID = "client_id";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>client_ip</tt>.<br>
     */
	 public static final String COLUMN_CLIENT_IP = "client_ip";
	/**
	 * This constant corresponds to db column <tt>gmt_live</tt>.<br>
     */
	 public static final String COLUMN_GMT_LIVE = "gmt_live";
	/**
	 * This constant corresponds to db column <tt>current_amount</tt>.<br>
     */
	 public static final String COLUMN_CURRENT_AMOUNT = "current_amount";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>client_host</tt>.<br>
     */
	 public static final String COLUMN_CLIENT_HOST = "client_host";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>client_id</tt>.<br>
     * 客户ID
     */
	private String clientId;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>client_ip</tt>.<br>
     * 客户端IP
     */
	private String clientIp;
	
	/**
	 * This property corresponds to db column <tt>gmt_live</tt>.<br>
     * 最后存活时间
     */
	private Date gmtLive;
	
	/**
	 * This property corresponds to db column <tt>current_amount</tt>.<br>
     * 当前处理数量
     */
	private long currentAmount;
	
	/**
	 * This property corresponds to db column <tt>status</tt>.<br>
     * 客户端状态
     */
	private String status;
	
	/**
	 * This property corresponds to db column <tt>client_host</tt>.<br>
     * 客户端主机名
     */
	private String clientHost;
	

    //========== getters and setters ==========

}
