/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_mail_server_config</tt>.<br>
 * 邮件发送通道配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_server_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="MailServerConfigDO对象", description="邮件发送通道配置")
@TableName("gtc_mail_server_config")
public class MailServerConfigDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_MAIL_SERVER_CONFIG";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>host</tt>.<br>
     */
	 public static final String COLUMN_HOST = "host";
	/**
	 * This constant corresponds to db column <tt>port</tt>.<br>
     */
	 public static final String COLUMN_PORT = "port";
	/**
	 * This constant corresponds to db column <tt>timeout</tt>.<br>
     */
	 public static final String COLUMN_TIMEOUT = "timeout";
	/**
	 * This constant corresponds to db column <tt>connect_timeout</tt>.<br>
     */
	 public static final String COLUMN_CONNECT_TIMEOUT = "connect_timeout";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>domain_name</tt>.<br>
     */
	 public static final String COLUMN_DOMAIN_NAME = "domain_name";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>host</tt>.<br>
     * 主机
     */
	private String host;
	
	/**
	 * This property corresponds to db column <tt>port</tt>.<br>
     * 端口
     */
	private int port;
	
	/**
	 * This property corresponds to db column <tt>timeout</tt>.<br>
     * 超时
     */
	private long timeout;
	
	/**
	 * This property corresponds to db column <tt>connect_timeout</tt>.<br>
     * 连接超时
     */
	private long connectTimeout;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>domain_name</tt>.<br>
     * 邮件域
     */
	private String domainName;
	

    //========== getters and setters ==========

}
