/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_mail_user_config</tt>.<br>
 * 邮件发送配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_user_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="MailUserConfigDO对象", description="邮件发送配置")
@TableName("gtc_mail_user_config")
public class MailUserConfigDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_MAIL_USER_CONFIG";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>password</tt>.<br>
     */
	 public static final String COLUMN_PASSWORD = "password";
	/**
	 * This constant corresponds to db column <tt>from_addr</tt>.<br>
     */
	 public static final String COLUMN_FROM_ADDR = "from_addr";
	/**
	 * This constant corresponds to db column <tt>mail_server_id</tt>.<br>
     */
	 public static final String COLUMN_MAIL_SERVER_ID = "mail_server_id";
	/**
	 * This constant corresponds to db column <tt>from_name</tt>.<br>
     */
	 public static final String COLUMN_FROM_NAME = "from_name";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>user_type</tt>.<br>
     */
	 public static final String COLUMN_USER_TYPE = "user_type";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>serverside_enabled</tt>.<br>
     */
	 public static final String COLUMN_SERVERSIDE_ENABLED = "serverside_enabled";
	/**
	 * This constant corresponds to db column <tt>serverside_disabled_reason</tt>.<br>
     */
	 public static final String COLUMN_SERVERSIDE_DISABLED_REASON = "serverside_disabled_reason";
	/**
	 * This constant corresponds to db column <tt>from_userword</tt>.<br>
     */
	 public static final String COLUMN_FROM_USERWORD = "from_userword";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>password</tt>.<br>
     * 发送人密码
     */
	private String password;
	
	/**
	 * This property corresponds to db column <tt>from_addr</tt>.<br>
     * 发送人地址
     */
	private String fromAddr;
	
	/**
	 * This property corresponds to db column <tt>mail_server_id</tt>.<br>
     * 发送的服务器ID
     */
	private long mailServerId;
	
	/**
	 * This property corresponds to db column <tt>from_name</tt>.<br>
     * 发送人姓名
     */
	private String fromName;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>user_type</tt>.<br>
     * 用户分类
     */
	private String userType;
	
	/**
	 * This property corresponds to db column <tt>status</tt>.<br>
     * 状态
     */
	private String status;
	
	/**
	 * This property corresponds to db column <tt>serverside_enabled</tt>.<br>
     * 用户在服务端是否有效
     */
	private boolean serversideEnabled;
	
	/**
	 * This property corresponds to db column <tt>serverside_disabled_reason</tt>.<br>
     * 服务端用户无效原因
     */
	private String serversideDisabledReason;
	
	/**
	 * This property corresponds to db column <tt>from_userword</tt>.<br>
     * 发件人用户名：用于发件时用户验证
     */
	private String fromUserword;
	

    //========== getters and setters ==========

}
