/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_mobile_client_setting</tt>.<br>
 * 移动客户端设置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mobile_client_setting.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="MobileClientSettingDO对象", description="移动客户端设置")
@TableName("gtc_mobile_client_setting")
public class MobileClientSettingDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_MOBILE_CLIENT_SETTING";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>login_key</tt>.<br>
     */
	 public static final String COLUMN_LOGIN_KEY = "login_key";
	/**
	 * This constant corresponds to db column <tt>sign_key</tt>.<br>
     */
	 public static final String COLUMN_SIGN_KEY = "sign_key";
	/**
	 * This constant corresponds to db column <tt>login_platform_type</tt>.<br>
     */
	 public static final String COLUMN_LOGIN_PLATFORM_TYPE = "login_platform_type";
	/**
	 * This constant corresponds to db column <tt>gmt_login</tt>.<br>
     */
	 public static final String COLUMN_GMT_LOGIN = "gmt_login";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>logined</tt>.<br>
     */
	 public static final String COLUMN_LOGINED = "logined";
	/**
	 * This constant corresponds to db column <tt>gmt_logout</tt>.<br>
     */
	 public static final String COLUMN_GMT_LOGOUT = "gmt_logout";
	/**
	 * This constant corresponds to db column <tt>notice_key</tt>.<br>
     */
	 public static final String COLUMN_NOTICE_KEY = "notice_key";
	/**
	 * This constant corresponds to db column <tt>notice_enabled</tt>.<br>
     */
	 public static final String COLUMN_NOTICE_ENABLED = "notice_enabled";
	/**
	 * This constant corresponds to db column <tt>gmt_notice_key_update</tt>.<br>
     */
	 public static final String COLUMN_GMT_NOTICE_KEY_UPDATE = "gmt_notice_key_update";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 会员Id
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>login_key</tt>.<br>
     * 登录key
     */
	private String loginKey;
	
	/**
	 * This property corresponds to db column <tt>sign_key</tt>.<br>
     * 签名key
     */
	private String signKey;
	
	/**
	 * This property corresponds to db column <tt>login_platform_type</tt>.<br>
     * 登录平台类型
     */
	private String loginPlatformType;
	
	/**
	 * This property corresponds to db column <tt>gmt_login</tt>.<br>
     * 登录时间
     */
	private Date gmtLogin;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>logined</tt>.<br>
     * 是否已登录
     */
	private boolean logined;
	
	/**
	 * This property corresponds to db column <tt>gmt_logout</tt>.<br>
     * 退出登录时间
     */
	private Date gmtLogout;
	
	/**
	 * This property corresponds to db column <tt>notice_key</tt>.<br>
     * 通知Key
     */
	private String noticeKey;
	
	/**
	 * This property corresponds to db column <tt>notice_enabled</tt>.<br>
     * 是否通知
     */
	private boolean noticeEnabled;
	
	/**
	 * This property corresponds to db column <tt>gmt_notice_key_update</tt>.<br>
     * 通知key更新时间
     */
	private Date gmtNoticeKeyUpdate;
	

    //========== getters and setters ==========

}
