/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_sms_black_list</tt>.<br>
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_black_list.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="SmsBlackListDO对象", description="")
@TableName("gtc_sms_black_list")
public class SmsBlackListDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_SMS_BLACK_LIST";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>intercept_object_type</tt>.<br>
     */
	 public static final String COLUMN_INTERCEPT_OBJECT_TYPE = "intercept_object_type";
	/**
	 * This constant corresponds to db column <tt>intercept_object_value</tt>.<br>
     */
	 public static final String COLUMN_INTERCEPT_OBJECT_VALUE = "intercept_object_value";
	/**
	 * This constant corresponds to db column <tt>memo</tt>.<br>
     */
	 public static final String COLUMN_MEMO = "memo";
	/**
	 * This constant corresponds to db column <tt>gmt_remove</tt>.<br>
     */
	 public static final String COLUMN_GMT_REMOVE = "gmt_remove";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>enabled</tt>.<br>
     */
	 public static final String COLUMN_ENABLED = "enabled";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 
     */
	 @TableId(type = IdType.NONE)
	private String id;
	
	/**
	 * This property corresponds to db column <tt>intercept_object_type</tt>.<br>
     * 
     */
	private String interceptObjectType;
	
	/**
	 * This property corresponds to db column <tt>intercept_object_value</tt>.<br>
     * 
     */
	private String interceptObjectValue;
	
	/**
	 * This property corresponds to db column <tt>memo</tt>.<br>
     * 
     */
	private String memo;
	
	/**
	 * This property corresponds to db column <tt>gmt_remove</tt>.<br>
     * 
     */
	private Date gmtRemove;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>enabled</tt>.<br>
     * 
     */
	private boolean enabled;
	

    //========== getters and setters ==========

}
