/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_sms_out_his</tt>.<br>
 * 已发送短信列表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_out_his.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="SmsOutHisDO对象", description="已发送短信列表")
@TableName("gtc_sms_out_his")
public class SmsOutHisDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_SMS_OUT_HIS";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>receiver</tt>.<br>
     */
	 public static final String COLUMN_RECEIVER = "receiver";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>gmt_resend</tt>.<br>
     */
	 public static final String COLUMN_GMT_RESEND = "gmt_resend";
	/**
	 * This constant corresponds to db column <tt>send_times</tt>.<br>
     */
	 public static final String COLUMN_SEND_TIMES = "send_times";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>sms_config_id</tt>.<br>
     */
	 public static final String COLUMN_SMS_CONFIG_ID = "sms_config_id";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>biz_id</tt>.<br>
     */
	 public static final String COLUMN_BIZ_ID = "biz_id";
	/**
	 * This constant corresponds to db column <tt>ack_code</tt>.<br>
     */
	 public static final String COLUMN_ACK_CODE = "ack_code";
	/**
	 * This constant corresponds to db column <tt>gmt_his_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_HIS_CREATE = "gmt_his_create";
	/**
	 * This constant corresponds to db column <tt>gmt_send_success</tt>.<br>
     */
	 public static final String COLUMN_GMT_SEND_SUCCESS = "gmt_send_success";
	/**
	 * This constant corresponds to db column <tt>ack_code_validate_count</tt>.<br>
     */
	 public static final String COLUMN_ACK_CODE_VALIDATE_COUNT = "ack_code_validate_count";
	/**
	 * This constant corresponds to db column <tt>send_result</tt>.<br>
     */
	 public static final String COLUMN_SEND_RESULT = "send_result";
	/**
	 * This constant corresponds to db column <tt>send_channel</tt>.<br>
     */
	 public static final String COLUMN_SEND_CHANNEL = "send_channel";
	/**
	 * This constant corresponds to db column <tt>send_sub_channel</tt>.<br>
     */
	 public static final String COLUMN_SEND_SUB_CHANNEL = "send_sub_channel";
	/**
	 * This constant corresponds to db column <tt>ack_code_validate_try_count</tt>.<br>
     */
	 public static final String COLUMN_ACK_CODE_VALIDATE_TRY_COUNT = "ack_code_validate_try_count";
	/**
	 * This constant corresponds to db column <tt>send_channel_specified</tt>.<br>
     */
	 public static final String COLUMN_SEND_CHANNEL_SPECIFIED = "send_channel_specified";
	/**
	 * This constant corresponds to db column <tt>resend_from_id</tt>.<br>
     */
	 public static final String COLUMN_RESEND_FROM_ID = "resend_from_id";
	/**
	 * This constant corresponds to db column <tt>sms_id</tt>.<br>
     */
	 public static final String COLUMN_SMS_ID = "sms_id";
	/**
	 * This constant corresponds to db column <tt>template_args</tt>.<br>
     */
	 public static final String COLUMN_TEMPLATE_ARGS = "template_args";
	/**
	 * This constant corresponds to db column <tt>unique_id</tt>.<br>
     */
	 public static final String COLUMN_UNIQUE_ID = "unique_id";
	/**
	 * This constant corresponds to db column <tt>app_code</tt>.<br>
     */
	 public static final String COLUMN_APP_CODE = "app_code";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，Pk
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>receiver</tt>.<br>
     * 接收人手机号
     */
	private String receiver;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 用户ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>content</tt>.<br>
     * 内容
     */
	private String content;
	
	/**
	 * This property corresponds to db column <tt>status</tt>.<br>
     * 状态
     */
	private String status;
	
	/**
	 * This property corresponds to db column <tt>gmt_resend</tt>.<br>
     * 下次重发时间
     */
	private Date gmtResend;
	
	/**
	 * This property corresponds to db column <tt>send_times</tt>.<br>
     * 发送次数
     */
	private int sendTimes;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>sms_config_id</tt>.<br>
     * 短信模板配置ID
     */
	private long smsConfigId;
	
	/**
	 * This property corresponds to db column <tt>properties</tt>.<br>
     * 消息属性
     */
	private String properties;
	
	/**
	 * This property corresponds to db column <tt>biz_id</tt>.<br>
     * 唯一业务号
     */
	private String bizId;
	
	/**
	 * This property corresponds to db column <tt>ack_code</tt>.<br>
     * 校验码，非校验类短信，此字段为空
     */
	private String ackCode;
	
	/**
	 * This property corresponds to db column <tt>gmt_his_create</tt>.<br>
     * 历史记录创建时间
     */
	private Date gmtHisCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_send_success</tt>.<br>
     * 成功发送时间
     */
	private Date gmtSendSuccess;
	
	/**
	 * This property corresponds to db column <tt>ack_code_validate_count</tt>.<br>
     * ACK_CODE验证成功次数
     */
	private int ackCodeValidateCount;
	
	/**
	 * This property corresponds to db column <tt>send_result</tt>.<br>
     * 发送结果
     */
	private String sendResult;
	
	/**
	 * This property corresponds to db column <tt>send_channel</tt>.<br>
     * 发送通道
     */
	private String sendChannel;
	
	/**
	 * This property corresponds to db column <tt>send_sub_channel</tt>.<br>
     * 发送子通道，由通道自行设置
     */
	private String sendSubChannel;
	
	/**
	 * This property corresponds to db column <tt>ack_code_validate_try_count</tt>.<br>
     * ACK_CODE尝试验证次数
     */
	private int ackCodeValidateTryCount;
	
	/**
	 * This property corresponds to db column <tt>send_channel_specified</tt>.<br>
     * 发送通道是否已指定，如果已指定，则不需要再次自动选择
     */
	private boolean sendChannelSpecified;
	
	/**
	 * This property corresponds to db column <tt>resend_from_id</tt>.<br>
     * 如果是重发短信，这里记录重发哪条短信
     */
	private long resendFromId;
	
	/**
	 * This property corresponds to db column <tt>sms_id</tt>.<br>
     * 短信ID
     */
	private String smsId;
	
	/**
	 * This property corresponds to db column <tt>template_args</tt>.<br>
     * 模板参数集合
     */
	private String templateArgs;
	
	/**
	 * This property corresponds to db column <tt>unique_id</tt>.<br>
     * 唯一ID，防止信息重复发送
     */
	private String uniqueId;
	
	/**
	 * This property corresponds to db column <tt>app_code</tt>.<br>
     * 应用代码
     */
	private String appCode;
	

    //========== getters and setters ==========

}
