/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_text_content</tt>.<br>
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_text_content.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="TextContentDO对象", description="")
@TableName("gtc_text_content")
public class TextContentDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_TEXT_CONTENT";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>owner_id</tt>.<br>
     */
	 public static final String COLUMN_OWNER_ID = "owner_id";
	/**
	 * This constant corresponds to db column <tt>owner_type</tt>.<br>
     */
	 public static final String COLUMN_OWNER_TYPE = "owner_type";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>deleted</tt>.<br>
     */
	 public static final String COLUMN_DELETED = "deleted";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>owner_id</tt>.<br>
     * 所有者ID
     */
	private String ownerId;
	
	/**
	 * This property corresponds to db column <tt>owner_type</tt>.<br>
     * 所有者类型
     */
	 @TableId(type = IdType.NONE)
	private String ownerType;
	
	/**
	 * This property corresponds to db column <tt>content</tt>.<br>
     * 内容
     */
	private String content;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 修改时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 创建时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>deleted</tt>.<br>
     * 是否删除
     */
	private boolean deleted;
	

    //========== getters and setters ==========

}
