/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>gtc_wx_gen_reply_msg_script</tt>.<br>
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_wx_gen_reply_msg_script.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="WxGenReplyMsgScriptDO对象", description="")
@TableName("gtc_wx_gen_reply_msg_script")
public class WxGenReplyMsgScriptDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "GTC_WX_GEN_REPLY_MSG_SCRIPT";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>code</tt>.<br>
     */
	 public static final String COLUMN_CODE = "code";
	/**
	 * This constant corresponds to db column <tt>name</tt>.<br>
     */
	 public static final String COLUMN_NAME = "name";
	/**
	 * This constant corresponds to db column <tt>support_check_script</tt>.<br>
     */
	 public static final String COLUMN_SUPPORT_CHECK_SCRIPT = "support_check_script";
	/**
	 * This constant corresponds to db column <tt>gen_reply_msg_script</tt>.<br>
     */
	 public static final String COLUMN_GEN_REPLY_MSG_SCRIPT = "gen_reply_msg_script";
	/**
	 * This constant corresponds to db column <tt>enabled</tt>.<br>
     */
	 public static final String COLUMN_ENABLED = "enabled";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>support_msg_type</tt>.<br>
     */
	 public static final String COLUMN_SUPPORT_MSG_TYPE = "support_msg_type";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>code</tt>.<br>
     * 
     */
	 @TableId(type = IdType.NONE)
	private String code;
	
	/**
	 * This property corresponds to db column <tt>name</tt>.<br>
     * 
     */
	private String name;
	
	/**
	 * This property corresponds to db column <tt>support_check_script</tt>.<br>
     * 
     */
	private String supportCheckScript;
	
	/**
	 * This property corresponds to db column <tt>gen_reply_msg_script</tt>.<br>
     * 
     */
	private String genReplyMsgScript;
	
	/**
	 * This property corresponds to db column <tt>enabled</tt>.<br>
     * 
     */
	private boolean enabled;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>support_msg_type</tt>.<br>
     * 支持的消息类型
     */
	private String supportMsgType;
	

    //========== getters and setters ==========

}
