/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_APP_CONFIG</tt>.<br> 
 * GOTONECORE应用配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_app_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_app_config",comments="GOTONECORE应用配置")
public class AppConfigTable {

	public static final String TABLE_NAME = "gtc_app_config";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>app_code</tt>.<br>
     */
	 @DBColumn(name="app_code",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="应用代码")
	 public static final String COLUMN_APP_CODE = "app_code";
	/**
	 * This constant corresponds to db column <tt>app_name</tt>.<br>
     */
	 @DBColumn(name="app_name",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="应用名称")
	 public static final String COLUMN_APP_NAME = "app_name";
	/**
	 * This constant corresponds to db column <tt>notify_url</tt>.<br>
     */
	 @DBColumn(name="notify_url",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="应用通知地址")
	 public static final String COLUMN_NOTIFY_URL = "notify_url";
	/**
	 * This constant corresponds to db column <tt>memo</tt>.<br>
     */
	 @DBColumn(name="memo",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="备注")
	 public static final String COLUMN_MEMO = "memo";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=false,comments="状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 @DBColumn(name="properties",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="属性集合")
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
}
