/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_MAIL_OUT_HISTORY</tt>.<br> 
 * 邮件发送历史表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_out_history.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_mail_out_history",comments="邮件发送历史表")
public class MailOutHistoryTable {

	public static final String TABLE_NAME = "gtc_mail_out_history";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(14,0)",dataDefault="",dataLength=14,dataPrecision=14,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>receiver</tt>.<br>
     */
	 @DBColumn(name="receiver",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=false,comments="接收人")
	 public static final String COLUMN_RECEIVER = "receiver";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 @DBColumn(name="user_id",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="用户ID")
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="char(1)",dataDefault="",dataLength=1,dataPrecision=0,dataScale=0,nullable=false,comments="状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>gmt_schedule</tt>.<br>
     */
	 @DBColumn(name="gmt_schedule",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="调度时间")
	 public static final String COLUMN_GMT_SCHEDULE = "gmt_schedule";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_mail_msg_create</tt>.<br>
     */
	 @DBColumn(name="gmt_mail_msg_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="邮件消息创建时间")
	 public static final String COLUMN_GMT_MAIL_MSG_CREATE = "gmt_mail_msg_create";
	/**
	 * This constant corresponds to db column <tt>mail_cc</tt>.<br>
     */
	 @DBColumn(name="mail_cc",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="抄送")
	 public static final String COLUMN_MAIL_CC = "mail_cc";
	/**
	 * This constant corresponds to db column <tt>mail_bcc</tt>.<br>
     */
	 @DBColumn(name="mail_bcc",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="密送")
	 public static final String COLUMN_MAIL_BCC = "mail_bcc";
	/**
	 * This constant corresponds to db column <tt>mail_replay_to</tt>.<br>
     */
	 @DBColumn(name="mail_replay_to",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="回复")
	 public static final String COLUMN_MAIL_REPLAY_TO = "mail_replay_to";
	/**
	 * This constant corresponds to db column <tt>mail_subject</tt>.<br>
     */
	 @DBColumn(name="mail_subject",dataType="varchar(128)",dataDefault="",dataLength=128,dataPrecision=0,dataScale=0,nullable=true,comments="主题")
	 public static final String COLUMN_MAIL_SUBJECT = "mail_subject";
	/**
	 * This constant corresponds to db column <tt>mail_from</tt>.<br>
     */
	 @DBColumn(name="mail_from",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="发送人")
	 public static final String COLUMN_MAIL_FROM = "mail_from";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 @DBColumn(name="properties",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="消息属性")
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>channel</tt>.<br>
     */
	 @DBColumn(name="channel",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="邮件通道")
	 public static final String COLUMN_CHANNEL = "channel";
	/**
	 * This constant corresponds to db column <tt>send_client_id</tt>.<br>
     */
	 @DBColumn(name="send_client_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="发送端ID")
	 public static final String COLUMN_SEND_CLIENT_ID = "send_client_id";
	/**
	 * This constant corresponds to db column <tt>mail_config_id</tt>.<br>
     */
	 @DBColumn(name="mail_config_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="邮件模板配置ID")
	 public static final String COLUMN_MAIL_CONFIG_ID = "mail_config_id";
	/**
	 * This constant corresponds to db column <tt>activity_id</tt>.<br>
     */
	 @DBColumn(name="activity_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="活动编号")
	 public static final String COLUMN_ACTIVITY_ID = "activity_id";
	/**
	 * This constant corresponds to db column <tt>send_times</tt>.<br>
     */
	 @DBColumn(name="send_times",dataType="decimal(2,0)",dataDefault="",dataLength=2,dataPrecision=2,dataScale=0,nullable=true,comments="发送次数")
	 public static final String COLUMN_SEND_TIMES = "send_times";
	/**
	 * This constant corresponds to db column <tt>template_args</tt>.<br>
     */
	 @DBColumn(name="template_args",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="模板参数")
	 public static final String COLUMN_TEMPLATE_ARGS = "template_args";
	/**
	 * This constant corresponds to db column <tt>mail_user_config_id</tt>.<br>
     */
	 @DBColumn(name="mail_user_config_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="发送的用户ID")
	 public static final String COLUMN_MAIL_USER_CONFIG_ID = "mail_user_config_id";
	/**
	 * This constant corresponds to db column <tt>mail_body_pattern</tt>.<br>
     */
	 @DBColumn(name="mail_body_pattern",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="邮件内容的生成模式")
	 public static final String COLUMN_MAIL_BODY_PATTERN = "mail_body_pattern";
}
