/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_MAIL_SEND_CLIENT</tt>.<br> 
 * 邮件发送客户端
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_send_client.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_mail_send_client",comments="邮件发送客户端")
public class MailSendClientTable {

	public static final String TABLE_NAME = "gtc_mail_send_client";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>client_id</tt>.<br>
     */
	 @DBColumn(name="client_id",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="客户ID")
	 public static final String COLUMN_CLIENT_ID = "client_id";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>client_ip</tt>.<br>
     */
	 @DBColumn(name="client_ip",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="客户端IP")
	 public static final String COLUMN_CLIENT_IP = "client_ip";
	/**
	 * This constant corresponds to db column <tt>gmt_live</tt>.<br>
     */
	 @DBColumn(name="gmt_live",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="最后存活时间")
	 public static final String COLUMN_GMT_LIVE = "gmt_live";
	/**
	 * This constant corresponds to db column <tt>current_amount</tt>.<br>
     */
	 @DBColumn(name="current_amount",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="当前处理数量")
	 public static final String COLUMN_CURRENT_AMOUNT = "current_amount";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=false,comments="客户端状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>client_host</tt>.<br>
     */
	 @DBColumn(name="client_host",dataType="varchar(128)",dataDefault="",dataLength=128,dataPrecision=0,dataScale=0,nullable=false,comments="客户端主机名")
	 public static final String COLUMN_CLIENT_HOST = "client_host";
}
