/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_MAIL_USER_CONFIG</tt>.<br> 
 * 邮件发送配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_mail_user_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_mail_user_config",comments="邮件发送配置")
public class MailUserConfigTable {

	public static final String TABLE_NAME = "gtc_mail_user_config";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>password</tt>.<br>
     */
	 @DBColumn(name="password",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="发送人密码")
	 public static final String COLUMN_PASSWORD = "password";
	/**
	 * This constant corresponds to db column <tt>from_addr</tt>.<br>
     */
	 @DBColumn(name="from_addr",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=false,comments="发送人地址")
	 public static final String COLUMN_FROM_ADDR = "from_addr";
	/**
	 * This constant corresponds to db column <tt>mail_server_id</tt>.<br>
     */
	 @DBColumn(name="mail_server_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="发送的服务器ID")
	 public static final String COLUMN_MAIL_SERVER_ID = "mail_server_id";
	/**
	 * This constant corresponds to db column <tt>from_name</tt>.<br>
     */
	 @DBColumn(name="from_name",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=false,comments="发送人姓名")
	 public static final String COLUMN_FROM_NAME = "from_name";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>user_type</tt>.<br>
     */
	 @DBColumn(name="user_type",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="用户分类")
	 public static final String COLUMN_USER_TYPE = "user_type";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>serverside_enabled</tt>.<br>
     */
	 @DBColumn(name="serverside_enabled",dataType="char(1)",dataDefault="",dataLength=1,dataPrecision=0,dataScale=0,nullable=true,comments="用户在服务端是否有效")
	 public static final String COLUMN_SERVERSIDE_ENABLED = "serverside_enabled";
	/**
	 * This constant corresponds to db column <tt>serverside_disabled_reason</tt>.<br>
     */
	 @DBColumn(name="serverside_disabled_reason",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="服务端用户无效原因")
	 public static final String COLUMN_SERVERSIDE_DISABLED_REASON = "serverside_disabled_reason";
	/**
	 * This constant corresponds to db column <tt>from_userword</tt>.<br>
     */
	 @DBColumn(name="from_userword",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="发件人用户名：用于发件时用户验证")
	 public static final String COLUMN_FROM_USERWORD = "from_userword";
}
