/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_SMS_CLIENT_SEND</tt>.<br> 
 * 短信客户端发送
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_client_send.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_sms_client_send",comments="短信客户端发送")
public class SmsClientSendTable {

	public static final String TABLE_NAME = "gtc_sms_client_send";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>sms_id</tt>.<br>
     */
	 @DBColumn(name="sms_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="短信ID")
	 public static final String COLUMN_SMS_ID = "sms_id";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=false,comments="状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_client_apply</tt>.<br>
     */
	 @DBColumn(name="gmt_client_apply",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="客户端申请时间")
	 public static final String COLUMN_GMT_CLIENT_APPLY = "gmt_client_apply";
	/**
	 * This constant corresponds to db column <tt>client_no</tt>.<br>
     */
	 @DBColumn(name="client_no",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="客户端号")
	 public static final String COLUMN_CLIENT_NO = "client_no";
	/**
	 * This constant corresponds to db column <tt>client_apply_count</tt>.<br>
     */
	 @DBColumn(name="client_apply_count",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="客户端申请次数")
	 public static final String COLUMN_CLIENT_APPLY_COUNT = "client_apply_count";
	/**
	 * This constant corresponds to db column <tt>gmt_client_send_finish</tt>.<br>
     */
	 @DBColumn(name="gmt_client_send_finish",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="客户端发送时间")
	 public static final String COLUMN_GMT_CLIENT_SEND_FINISH = "gmt_client_send_finish";
	/**
	 * This constant corresponds to db column <tt>gmt_client_resend</tt>.<br>
     */
	 @DBColumn(name="gmt_client_resend",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="下次发送时间")
	 public static final String COLUMN_GMT_CLIENT_RESEND = "gmt_client_resend";
	/**
	 * This constant corresponds to db column <tt>client_apply_batch_id</tt>.<br>
     */
	 @DBColumn(name="client_apply_batch_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="客户端申请批次号")
	 public static final String COLUMN_CLIENT_APPLY_BATCH_ID = "client_apply_batch_id";
}
