/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_SMS_CONFIG_IN_CHANNEL</tt>.<br> 
 * 短信配置在通道方的配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_config_in_channel.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_sms_config_in_channel",comments="短信配置在通道方的配置")
public class SmsConfigInChannelTable {

	public static final String TABLE_NAME = "gtc_sms_config_in_channel";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>sms_config_id</tt>.<br>
     */
	 @DBColumn(name="sms_config_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="短信配置ID")
	 public static final String COLUMN_SMS_CONFIG_ID = "sms_config_id";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 @DBColumn(name="content",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="")
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>channel</tt>.<br>
     */
	 @DBColumn(name="channel",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="")
	 public static final String COLUMN_CHANNEL = "channel";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>enabled</tt>.<br>
     */
	 @DBColumn(name="enabled",dataType="decimal(1,0)",dataDefault="",dataLength=1,dataPrecision=1,dataScale=0,nullable=true,comments="")
	 public static final String COLUMN_ENABLED = "enabled";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 @DBColumn(name="properties",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="")
	 public static final String COLUMN_PROPERTIES = "properties";
}
