/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_SMS_CONFIG</tt>.<br> 
 * 短信配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_sms_config",comments="短信配置")
public class SmsConfigTable {

	public static final String TABLE_NAME = "gtc_sms_config";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>config_name</tt>.<br>
     */
	 @DBColumn(name="config_name",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="模板配置名")
	 public static final String COLUMN_CONFIG_NAME = "config_name";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 @DBColumn(name="content",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="短信内容")
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>send_channels</tt>.<br>
     */
	 @DBColumn(name="send_channels",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="发送通道，多个逗号间隔，系统按权重，可用性等进行排序后，返回一个通道，如果不配置，则再全部通道中查找")
	 public static final String COLUMN_SEND_CHANNELS = "send_channels";
	/**
	 * This constant corresponds to db column <tt>interval_seconds</tt>.<br>
     */
	 @DBColumn(name="interval_seconds",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="重复发送间隔时间，如果是5分钟，表明5分钟内只允许发送1次")
	 public static final String COLUMN_INTERVAL_SECONDS = "interval_seconds";
	/**
	 * This constant corresponds to db column <tt>ack_code_timeout_seconds</tt>.<br>
     */
	 @DBColumn(name="ack_code_timeout_seconds",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="验证ACKCode的超时时间，小于等于0表示不限制")
	 public static final String COLUMN_ACK_CODE_TIMEOUT_SECONDS = "ack_code_timeout_seconds";
	/**
	 * This constant corresponds to db column <tt>ack_code_max_validate</tt>.<br>
     */
	 @DBColumn(name="ack_code_max_validate",dataType="decimal(5,0)",dataDefault="",dataLength=5,dataPrecision=5,dataScale=0,nullable=true,comments="验证码最多验证次数，小于等于0表示不限制")
	 public static final String COLUMN_ACK_CODE_MAX_VALIDATE = "ack_code_max_validate";
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>send_start_time</tt>.<br>
     */
	 @DBColumn(name="send_start_time",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="开始发送时间，24小时制，08:00:00")
	 public static final String COLUMN_SEND_START_TIME = "send_start_time";
	/**
	 * This constant corresponds to db column <tt>send_end_time</tt>.<br>
     */
	 @DBColumn(name="send_end_time",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="截止发送时间，24小时制，22:00:00")
	 public static final String COLUMN_SEND_END_TIME = "send_end_time";
	/**
	 * This constant corresponds to db column <tt>max_try_count</tt>.<br>
     */
	 @DBColumn(name="max_try_count",dataType="decimal(2,0)",dataDefault="",dataLength=2,dataPrecision=2,dataScale=0,nullable=true,comments="最大发送重试次数")
	 public static final String COLUMN_MAX_TRY_COUNT = "max_try_count";
	/**
	 * This constant corresponds to db column <tt>retry_interval_seconds</tt>.<br>
     */
	 @DBColumn(name="retry_interval_seconds",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="发送失败后，重试间隔秒数")
	 public static final String COLUMN_RETRY_INTERVAL_SECONDS = "retry_interval_seconds";
	/**
	 * This constant corresponds to db column <tt>sms_out_need_unique_id</tt>.<br>
     */
	 @DBColumn(name="sms_out_need_unique_id",dataType="decimal(1,0)",dataDefault="",dataLength=1,dataPrecision=1,dataScale=0,nullable=true,comments="短信发送是否需要唯一id")
	 public static final String COLUMN_SMS_OUT_NEED_UNIQUE_ID = "sms_out_need_unique_id";
}
