/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_SMS_CLIENT</tt>.<br> 
 * 短信发送客户端
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_client.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_sms_client",comments="短信发送客户端")
public class SmsClientTable {

	public static final String TABLE_NAME = "gtc_sms_client";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，PK")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>client_no</tt>.<br>
     */
	 @DBColumn(name="client_no",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="客户端号")
	 public static final String COLUMN_CLIENT_NO = "client_no";
	/**
	 * This constant corresponds to db column <tt>login_password</tt>.<br>
     */
	 @DBColumn(name="login_password",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=false,comments="登录密码")
	 public static final String COLUMN_LOGIN_PASSWORD = "login_password";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>enabled</tt>.<br>
     */
	 @DBColumn(name="enabled",dataType="decimal(1,0)",dataDefault="",dataLength=1,dataPrecision=1,dataScale=0,nullable=false,comments="是否有效")
	 public static final String COLUMN_ENABLED = "enabled";
	/**
	 * This constant corresponds to db column <tt>sign_key</tt>.<br>
     */
	 @DBColumn(name="sign_key",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="签名key")
	 public static final String COLUMN_SIGN_KEY = "sign_key";
	/**
	 * This constant corresponds to db column <tt>apply_each_count</tt>.<br>
     */
	 @DBColumn(name="apply_each_count",dataType="decimal(4,0)",dataDefault="",dataLength=4,dataPrecision=4,dataScale=0,nullable=true,comments="每次申请的短信数")
	 public static final String COLUMN_APPLY_EACH_COUNT = "apply_each_count";
	/**
	 * This constant corresponds to db column <tt>apply_max_pool_size</tt>.<br>
     */
	 @DBColumn(name="apply_max_pool_size",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="申请的池最大容量")
	 public static final String COLUMN_APPLY_MAX_POOL_SIZE = "apply_max_pool_size";
	/**
	 * This constant corresponds to db column <tt>sign_type</tt>.<br>
     */
	 @DBColumn(name="sign_type",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="签名类型")
	 public static final String COLUMN_SIGN_TYPE = "sign_type";
}
