/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_SMS_OUT_HIS</tt>.<br> 
 * 已发送短信列表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_sms_out_his.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_sms_out_his",comments="已发送短信列表")
public class SmsOutHisTable {

	public static final String TABLE_NAME = "gtc_sms_out_his";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 @DBColumn(name="id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=false,comments="主键，Pk")
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>receiver</tt>.<br>
     */
	 @DBColumn(name="receiver",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=false,comments="接收人手机号")
	 public static final String COLUMN_RECEIVER = "receiver";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 @DBColumn(name="user_id",dataType="varchar(128)",dataDefault="",dataLength=128,dataPrecision=0,dataScale=0,nullable=true,comments="用户ID")
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 @DBColumn(name="content",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="内容")
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 @DBColumn(name="status",dataType="char(1)",dataDefault="",dataLength=1,dataPrecision=0,dataScale=0,nullable=false,comments="状态")
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>gmt_resend</tt>.<br>
     */
	 @DBColumn(name="gmt_resend",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="下次重发时间")
	 public static final String COLUMN_GMT_RESEND = "gmt_resend";
	/**
	 * This constant corresponds to db column <tt>send_times</tt>.<br>
     */
	 @DBColumn(name="send_times",dataType="decimal(2,0)",dataDefault="",dataLength=2,dataPrecision=2,dataScale=0,nullable=true,comments="发送次数")
	 public static final String COLUMN_SEND_TIMES = "send_times";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>sms_config_id</tt>.<br>
     */
	 @DBColumn(name="sms_config_id",dataType="decimal(14,0)",dataDefault="",dataLength=14,dataPrecision=14,dataScale=0,nullable=true,comments="短信模板配置ID")
	 public static final String COLUMN_SMS_CONFIG_ID = "sms_config_id";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 @DBColumn(name="properties",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="消息属性")
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>biz_id</tt>.<br>
     */
	 @DBColumn(name="biz_id",dataType="varchar(128)",dataDefault="",dataLength=128,dataPrecision=0,dataScale=0,nullable=false,comments="唯一业务号")
	 public static final String COLUMN_BIZ_ID = "biz_id";
	/**
	 * This constant corresponds to db column <tt>ack_code</tt>.<br>
     */
	 @DBColumn(name="ack_code",dataType="varchar(8)",dataDefault="",dataLength=8,dataPrecision=0,dataScale=0,nullable=true,comments="校验码，非校验类短信，此字段为空")
	 public static final String COLUMN_ACK_CODE = "ack_code";
	/**
	 * This constant corresponds to db column <tt>gmt_his_create</tt>.<br>
     */
	 @DBColumn(name="gmt_his_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="历史记录创建时间")
	 public static final String COLUMN_GMT_HIS_CREATE = "gmt_his_create";
	/**
	 * This constant corresponds to db column <tt>gmt_send_success</tt>.<br>
     */
	 @DBColumn(name="gmt_send_success",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=true,comments="成功发送时间")
	 public static final String COLUMN_GMT_SEND_SUCCESS = "gmt_send_success";
	/**
	 * This constant corresponds to db column <tt>ack_code_validate_count</tt>.<br>
     */
	 @DBColumn(name="ack_code_validate_count",dataType="decimal(5,0)",dataDefault="",dataLength=5,dataPrecision=5,dataScale=0,nullable=true,comments="ACK_CODE验证成功次数")
	 public static final String COLUMN_ACK_CODE_VALIDATE_COUNT = "ack_code_validate_count";
	/**
	 * This constant corresponds to db column <tt>send_result</tt>.<br>
     */
	 @DBColumn(name="send_result",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="发送结果")
	 public static final String COLUMN_SEND_RESULT = "send_result";
	/**
	 * This constant corresponds to db column <tt>send_channel</tt>.<br>
     */
	 @DBColumn(name="send_channel",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="发送通道")
	 public static final String COLUMN_SEND_CHANNEL = "send_channel";
	/**
	 * This constant corresponds to db column <tt>send_sub_channel</tt>.<br>
     */
	 @DBColumn(name="send_sub_channel",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="发送子通道，由通道自行设置")
	 public static final String COLUMN_SEND_SUB_CHANNEL = "send_sub_channel";
	/**
	 * This constant corresponds to db column <tt>ack_code_validate_try_count</tt>.<br>
     */
	 @DBColumn(name="ack_code_validate_try_count",dataType="decimal(5,0)",dataDefault="",dataLength=5,dataPrecision=5,dataScale=0,nullable=true,comments="ACK_CODE尝试验证次数")
	 public static final String COLUMN_ACK_CODE_VALIDATE_TRY_COUNT = "ack_code_validate_try_count";
	/**
	 * This constant corresponds to db column <tt>send_channel_specified</tt>.<br>
     */
	 @DBColumn(name="send_channel_specified",dataType="decimal(1,0)",dataDefault="",dataLength=1,dataPrecision=1,dataScale=0,nullable=true,comments="发送通道是否已指定，如果已指定，则不需要再次自动选择")
	 public static final String COLUMN_SEND_CHANNEL_SPECIFIED = "send_channel_specified";
	/**
	 * This constant corresponds to db column <tt>resend_from_id</tt>.<br>
     */
	 @DBColumn(name="resend_from_id",dataType="decimal(15,0)",dataDefault="",dataLength=15,dataPrecision=15,dataScale=0,nullable=true,comments="如果是重发短信，这里记录重发哪条短信")
	 public static final String COLUMN_RESEND_FROM_ID = "resend_from_id";
	/**
	 * This constant corresponds to db column <tt>sms_id</tt>.<br>
     */
	 @DBColumn(name="sms_id",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="短信ID")
	 public static final String COLUMN_SMS_ID = "sms_id";
	/**
	 * This constant corresponds to db column <tt>template_args</tt>.<br>
     */
	 @DBColumn(name="template_args",dataType="text",dataDefault="",dataLength=65535,dataPrecision=0,dataScale=0,nullable=true,comments="模板参数集合")
	 public static final String COLUMN_TEMPLATE_ARGS = "template_args";
	/**
	 * This constant corresponds to db column <tt>unique_id</tt>.<br>
     */
	 @DBColumn(name="unique_id",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=true,comments="唯一ID，防止信息重复发送")
	 public static final String COLUMN_UNIQUE_ID = "unique_id";
	/**
	 * This constant corresponds to db column <tt>app_code</tt>.<br>
     */
	 @DBColumn(name="app_code",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="应用代码")
	 public static final String COLUMN_APP_CODE = "app_code";
}
