/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_TEXT_CONTENT</tt>.<br> 
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_text_content.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_text_content",comments="")
public class TextContentTable {

	public static final String TABLE_NAME = "gtc_text_content";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>owner_id</tt>.<br>
     */
	 @DBColumn(name="owner_id",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="所有者ID")
	 public static final String COLUMN_OWNER_ID = "owner_id";
	/**
	 * This constant corresponds to db column <tt>owner_type</tt>.<br>
     */
	 @DBColumn(name="owner_type",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=false,comments="所有者类型")
	 public static final String COLUMN_OWNER_TYPE = "owner_type";
	/**
	 * This constant corresponds to db column <tt>content</tt>.<br>
     */
	 @DBColumn(name="content",dataType="LONGVARBINARY",dataDefault="",dataLength=-1,dataPrecision=0,dataScale=0,nullable=false,comments="内容")
	 public static final String COLUMN_CONTENT = "content";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="修改时间")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="创建时间")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>deleted</tt>.<br>
     */
	 @DBColumn(name="deleted",dataType="char(1)",dataDefault="",dataLength=1,dataPrecision=0,dataScale=0,nullable=true,comments="是否删除")
	 public static final String COLUMN_DELETED = "deleted";
}
