/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.gotonecore.repository.table;

import com.bench.common.annotation.DBTable;
import com.bench.common.annotation.DBColumn;

/**
 * A table description for database table <tt>GTC_WX_GEN_REPLY_MSG_SCRIPT</tt>.<br> 
 * 
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/gtc_wx_gen_reply_msg_script.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author nowli
 */
@DBTable(name="gtc_wx_gen_reply_msg_script",comments="")
public class WxGenReplyMsgScriptTable {

	public static final String TABLE_NAME = "gtc_wx_gen_reply_msg_script";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>code</tt>.<br>
     */
	 @DBColumn(name="code",dataType="varchar(64)",dataDefault="",dataLength=64,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_CODE = "code";
	/**
	 * This constant corresponds to db column <tt>name</tt>.<br>
     */
	 @DBColumn(name="name",dataType="varchar(128)",dataDefault="",dataLength=128,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_NAME = "name";
	/**
	 * This constant corresponds to db column <tt>support_check_script</tt>.<br>
     */
	 @DBColumn(name="support_check_script",dataType="LONGVARBINARY",dataDefault="",dataLength=-1,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_SUPPORT_CHECK_SCRIPT = "support_check_script";
	/**
	 * This constant corresponds to db column <tt>gen_reply_msg_script</tt>.<br>
     */
	 @DBColumn(name="gen_reply_msg_script",dataType="LONGVARBINARY",dataDefault="",dataLength=-1,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GEN_REPLY_MSG_SCRIPT = "gen_reply_msg_script";
	/**
	 * This constant corresponds to db column <tt>enabled</tt>.<br>
     */
	 @DBColumn(name="enabled",dataType="decimal(1,0)",dataDefault="",dataLength=1,dataPrecision=1,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_ENABLED = "enabled";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 @DBColumn(name="gmt_modified",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 @DBColumn(name="gmt_create",dataType="datetime",dataDefault="",dataLength=0,dataPrecision=0,dataScale=0,nullable=false,comments="")
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>support_msg_type</tt>.<br>
     */
	 @DBColumn(name="support_msg_type",dataType="varchar(32)",dataDefault="",dataLength=32,dataPrecision=0,dataScale=0,nullable=true,comments="支持的消息类型")
	 public static final String COLUMN_SUPPORT_MSG_TYPE = "support_msg_type";
}
